"""create notify tables

Revision ID: 3a74860c47f4
Revises: 
Create Date: 2026-09-14 14:02:52.568104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a74860c47f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify_failed_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('permanent', sa.Boolean(), nullable=False),
    sa.Column('raw_message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_failed_record_request_id'), 'notify_failed_record', ['request_id'], unique=False)
    op.create_table('notify_gateway_call',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('error_msg', sa.String(length=256), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_gateway_call_channel'), 'notify_gateway_call', ['channel'], unique=False)
    op.create_index(op.f('ix_notify_gateway_call_request_id'), 'notify_gateway_call', ['request_id'], unique=False)
    op.create_table('notify_send_record',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('biz_type', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('request_id', 'channel', name='uq_send_request_channel')
    )
    op.create_index(op.f('ix_notify_send_record_channel'), 'notify_send_record', ['channel'], unique=False)
    op.create_index(op.f('ix_notify_send_record_request_id'), 'notify_send_record', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notify_send_record_request_id'), table_name='notify_send_record')
    op.drop_index(op.f('ix_notify_send_record_channel'), table_name='notify_send_record')
    op.drop_table('notify_send_record')
    op.drop_index(op.f('ix_notify_gateway_call_request_id'), table_name='notify_gateway_call')
    op.drop_index(op.f('ix_notify_gateway_call_channel'), table_name='notify_gateway_call')
    op.drop_table('notify_gateway_call')
    op.drop_index(op.f('ix_notify_failed_record_request_id'), table_name='notify_failed_record')
    op.drop_table('notify_failed_record')
    # ### end Alembic commands ###
