"""创建锁教程实验表

Revision ID: de0fe7eab187
Revises:
Create Date: 2026-09-30 10:46:38.427993

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de0fe7eab187"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lock_lab_product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("available", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_table(
        "lock_lab_order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("request_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["lock_lab_product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lock_lab_order")
    op.drop_table("lock_lab_product")
    # ### end Alembic commands ###
